"""
SIMILAR A UN ARRAY EN JS, SON COLLECTIONS DE DATA, ESTOS EN PARTICULAR 
TIENE LA CUALIDAD DE QUE TAMBIEN ES DATA HETEROGENEA Y QUE TE PERMITE USAR EN ITERACIONES DE MANERA 
PROGRESIVA Y QUE SE PUEDE RECORRER DEPENDIENDO DE LA FORMA QUE QUERRAMOS
RECORRERLO, LO VEREMOS UN POCO MAS ADELANTE  PUES AL IGUAL QUE EN JS 
TAMBIEN TIENE DISTINTAS PROPIEDADES Y METODOS
"""

nombre:list = [ lambda x: x , "pato",11,{"dni":987123}, 23_232_232]

for _ in nombre:
    print(_)
