version: "3.9"

services:
    mysql:
        image: mysql:v0.1
        container_name: mysql
        build:
            context: .
            dockerfile: ./db/Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306"
        healthcheck:
            test:
                [
                    "CMD",
                    "mysql",
                    "-u",
                    "root",
                    "-padmin",
                    "-e",
                    "USE products_api_base;",
                ]
            retries: 2
        networks:
            django_network:
                aliases:
                    - mysql_host

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

        networks:
            django_network:
                aliases:
                    - adminer_host

    django:
        image: django:0.0.1
        container_name: django
        build:
            context: .
            dockerfile: ./django/Dockerfile
        ports:
            - "8000:8000"

        networks:
            django_network:
                aliases:
                    - django_host

        volumes:
            - media:/src/media
            - staticfiles:/src/staticfiles
        env_file:
            - envfiles/production.env
        depends_on:
            mysql:
                condition: service_healthy

    nginx:
        container_name: nginx
        build:
            context: ./nginx/
        volumes:
            - media:/home/app/media
            - staticfiles:/home/app/staticfiles
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - django

        networks:
            django_network:
                aliases:
                    - nginx_host

networks:
    django_network:
        name: django-net
        driver: bridge
        ipam:
            driver: default

volumes:
    staticfiles:
    media:
