version: "3.9"

services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx/
        volumes:
            - staticfiles:/home/app/staticfiles
            - ./nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - django

        networks:
            django_network:
                aliases:
                    - nginx_host

    django:
        image: django:0.0.1
        container_name: django
        build:
            context: .
            dockerfile: ./django/Dockerfile
        ports:
            - "8000:8000"

        networks:
            django_network:
                aliases:
                    - django_host

        volumes:
            - staticfiles:/src/staticfiles
        env_file:
            - .env_variables/production.env
        depends_on:
            - django


    mysql:
        image: mysql:v0.1
        container_name: mysql
        build:
            context: .
            dockerfile: ./db/Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3307:3306"
        networks:
            django_network:
                aliases:
                    - mysql_host

networks:
    django_network:
        name: django-net
        driver: bridge
        ipam:
            driver: default

volumes:
    staticfiles:
